### ISSUE TITLE
Switch from rust_sodium to native Rust crypto libraries

### ISSUE THREAD

**Issue by nbaksalyar** [maidsafe/safe_client_libs#1039]
1. Replace signatures & asymmetric encryption with BLS.
2. Replace symmetric encryption with Miscreant.
3. Replace PBKDF2 with `rust-crypto` or something similar.

## Update

Looks like `safe_core` docs failed to build because it couldn't download `rust_sodium`, due to the new sandbox limits:
https://docs.rs/crate/safe_core/0.35.0/builds
I wanted to request them to unblock network access, but looks like it's not possible:
```
<!-- Please note we *won't* enable network access or allow
     the crate to write in read-only directories, to avoid
     compromising the security of docs.rs itself. -->
```
So `rust_sodium` needs to be **completely** removed as a SCL dependency, including from **`self_encryption`**.

## Sub-tasks:
- [x] maidsafe/self_encryption#254
- [x] #1079
- [x] #1080
- [x] #1081
- [x] #1082
- [x] #1083

**Comment by kitlith** [comment]
Do you want to replace the symmetric and asymmetric algorithms entirely with something else? Or replace them with something that is compatible, just written in rust?

For the former:
 1. [`bls-like`](https://docs.rs/bls-like/0.1.0/bls_like/) is more recently maintained than [`bls`](https://github.com/str4d/bls)
 2. [`miscreant`](https://docs.rs/miscreant/0.4.2/miscreant/)
 3. I'm not sure which specific algorithm you want to move to, since you don't appear to currently be using PBKDF2.

For the latter:
 1. [`rust_sodium::crypto::box_`](https://docs.rs/rust_sodium/0.10.2/rust_sodium/crypto/box_/index.html) is curve25519xsalsa20poly1305, so maybe a combination of [`curve25519-dalek`](https://doc.dalek.rs/curve25519_dalek/) and [`xsalsa20poly1305`](https://docs.rs/xsalsa20poly1305/0.2.0/xsalsa20poly1305/)?
 2. [`rust_sodium::crypto::secretbox`](https://docs.rs/rust_sodium/0.10.2/rust_sodium/crypto/secretbox/index.html) -> [`xsalsa20poly1305`](https://docs.rs/xsalsa20poly1305/0.2.0/xsalsa20poly1305/)
 3. [`rust_sodium::crypto::pwhash`](https://docs.rs/rust_sodium/0.10.2/rust_sodium/crypto/pwhash/index.html) which is scryptsalsa208sha256 (not PBKDF2?), so maybe a combination of [`scrypt`](https://docs.rs/scrypt/0.2.0/scrypt/), [`salsa20`](https://docs.rs/salsa20/0.3.0/salsa20/), and [`sha2`](https://docs.rs/sha2/0.8.0/sha2/) ?

As a side note, you probably want to avoid using rust-crypto which has been unmaintained for 3 years and instead, say, use crates from the [RustCrypto](https://github.com/RustCrypto) project.

**Comment by dirvine** [comment]
Just note that rust_sodium is a wrapper around a c lib that can cause build hassles. We are looking to be pure rust where possible to allow targetting multiple platforms easily. 

bls_like and rustcrypto are likely good calls, although we along with similar projects are pretty happy with pairing crate and the work around that being done. We will have use of several symmetric ciphers and algos, for instance in self_encryption we dont need AEAD but it may be useful in SCL for some use cases, salsa/aes(cbc or simlar) may be best in others, especially when we are streaming.

Just for info though and thanks for the feeback, really appreicated.

**Comment by kitlith** [comment]
I figured that's why you were switching away from rust_sodium. And pairing is probably a better bet than bls-like, I just couldn't find it with the keywords I was using.

I'd like to help w/ a PR if I can, but if you're switching algos entirely, I'm not sure I'm qualified to make the decisions for that, heh.

**Comment by dirvine** [comment]
We would love to help walk you through that. Please feel free to take a shot. For symm we cna use miscreant or aes gcm or similar. No biggie, we can debate that during the PR. For PBKDF we are all good to. If you start with the algos from the rustcrypto project there and we use threshold_crypto for BLS (to stay consistent) then fire away. The guys will love the help and this is OSS we need to get as many hands on keybaords as possible. 
Of course you may want to start smaller, but this is a good one and a real PITA for us right now with ci and deployments. So feel free and don't worrry at all.

**Comment by lionel1704** [comment]
Migration is complete in the PRs linked to the individual issues in the description.
New versions of the crates have been published and the documentation has successfully built and published on docs.rs.
