### ISSUE TITLE
Refactor the usage of containers for an account

### ISSUE THREAD

**Issue by lionel1704** [maidsafe/safe_client_libs#1061]
Currently, every account has a number of default containers. The access to these containers is maintained in the `access_container`. As discussed the following changes are proposed:

- [x] Remove the creation of the default containers.
- [x] When an app requests for a container, the authenticator will prompt the user about the request and depending on the existence of the container either of the following will happen:
          - **Container exitsts:** The app is given access to the container
          - **Doesn't exist:** The container will be created and the app will be given access to it.

- [x] Add a `containers-list` entry to the access container.
          This entry will hold a vector of the different containers available. This entry is not encrypted so that authorised apps can read the list of containers available.

**Additional nice-to-haves:**
- [ ] Restrict the creation of the access container until the first container is created.

**Comment by theWebalyst** [comment]
Nice for efficiency, and maybe makes creating new account cheaper?

Possible downside is more containers created than needed such as Pictures, Images, Photos, Drawings (as per app developer preference) rather than the developer seeing that Pictures always exists and deciding to use that rather than create their own.

Another possible issue is localisation. I'm not sure if it's colonial to 'suggest' English names by having them created by default (as now) or have apps developed in Russia, China, Vietnam and of course France :wink: using their own language for standard containers which Devs from other countries won't recognise.

Maybe this is something that RDF can help with? For ex, by having a semantic label which helps an app identify the purpose of a container regardless of the name. But if they are created by apps on first access that's unlikely to happen unless the API has some way to nudge in that direction. I'm not sure it would be picked up anyway, just a thought.

**Comment by lionel1704** [comment]
Yes @theWebalyst. Account creation is now cheaper.
You make a good point about the possibility of unnecessary containers as well. The reason we're introducing this is to increase the flexibility for developers and to prevent users for paying for containers they don't necessarily use. For example, a user might create an account just to manage his safecoin.

RDF will definitely help with this. Once we introduce RDF, there are endless possibilities and I for one am super excited about it!

**Comment by lionel1704** [comment]
Closing this in favor of the [labelled data pre RFC](https://safenetforum.org/t/pre-rfc-labelled-data/30497/32) which supersedes the concept of containers.
