### ISSUE TITLE
dns name "more than one" full stop?..

### ISSUE THREAD

**Issue by davidpbrown** [maidsafe/safe_client_libs#457]
In https://github.com/maidsafe/safe_client_libs/blob/master/examples/simulate_browser.rs
thrown by reading this suggestion of more than one period in a dns name:
```
 fn create_dns_record 
99    println!("\nEnter Dns Name (eg., pepsico.com [Note: more than one \".\"s are not allowed in \
              this simple example]):");
```
Is that correct.. or are no \".\"s allowed?

Wondering also then there are a number of suggestions of 
```println!("\nEnter Dns Name (eg., pepsico.com):");```
rather than 
```println!("\nEnter Dns Name (eg., pepsico):");```

Is that signalling a change to adopt more familiar dot com like dns names?.. If so, I can't quite see that the parsing of urls is insisting on that form and requiring a period. Teasing that pepsico.com might see such .com entered.

**Comment by ustulation** [comment]
There is no set rule for anything in the main crate. As the comment you linked above says -
> ... this simple example ...

It is just for the sake of usage of dns module (which is going to be deprecated once `dev` is merged to `master` because the whole paradigm has changed with authenticator etc.). The actual usage for this `master` is demoed in `safe_demo_app` (`safe_examples`) binary which is usually released with test-nets/alpha.
