### ISSUE TITLE
Error [E0308] when trying to compile on Arch Linux

### ISSUE THREAD

**Issue by penguwin** [maidsafe/safe_client_libs#559]
I don't really know where I'm going wrong. 

Always getting a compiler error while building with:
`cargo build --release --feature use-mock-routing`

Current installed and active  toolchain:
`nightly-x86_64-unknown-linux-gnu (default)`
`rustc 1.21.0-nightly (003a929f9 2017-08-26)`

Operating system:
`x86_64 Linux 4.12.8-2-ARCH`

Always getting an error while compiling a fresh cloned repo:

> Compiling safe_core v0.26.1 (file:///home/penguwin/code/maidsafe/safe_client_libs/safe_core)
> error[E0308]: mismatched types
>    --> safe_core/src/utils/mod.rs:130:6
>     |
> 130 |     (password, keyword, pin)
>     |      ^^^^^^^^ expected"struct std::vec::Vec, found array of 64 elements
>     |
>     = note: expected type "std::vec::Vec<u8>"
>                found type [u8; 64]
>     = help: here are some functions which might fulfill your needs:
>             - .to_vec()
> 
> error[E0308]: mismatched types
>    --> safe_core/src/utils/mod.rs:130:16
>     |
> 130 |     (password, keyword, pin)
>     |                ^^^^^^^ expected struct std::vec::Vec, found array of 64 elements
>     |
>     = note: expected type std::vec::Vec<u8>
>                found type [u8; 64]
>     = help: here are some functions which might fulfill your needs:
>             - .to_vec()
> 
> error[E0308]: mismatched types
>    --> safe_core/src/utils/mod.rs:130:25
>     |
> 130 |     (password, keyword, pin)
>     |                         ^^^ expected struct std::vec::Vec, found array of 64 elements
>     |
>     = note: expected type std::vec::Vec<u8>
>                found type [u8; 64]
>     = help: here are some functions which might fulfill your needs:
>             - .to_vec()
> 
> error: aborting due to 3 previous errors
> 
> error: Could not compile safe_core.
> 
> To learn more, run the command again with --verbose.

**Comment by Fraser999** [comment]
Hi there,

The issue here is simply that you're using Rust nightly to build this, whereas we only support and test with Rust stable 1.19.0<sup>*</sup>.

We usually keep more-or-less in sync with Rust's own release schedule, so within a few days of stable 1.20.0 being released, we'll likely upgrade to use that.  This gives us a bit of breathing room to fix issues like this where currently-compiling code breaks due to language or std library changes.

Probably the best place to see which version we're currently using is inside the [AppVeyor CI script](https://github.com/maidsafe/safe_client_libs/blob/master/appveyor.yml#L6).

<sup>*</sup> We run clippy as part of our CI tests and this requires use of a nightly release, but we fix that to a specific version at the same point when we go to a new stable version.  However, we're only running our test suites using Rust stable.

**Comment by penguwin** [comment]
Thank you for the fast and detailed response :)
Everything works/compiles now flawless with the stable toolchain. 
I'm sorry for the circumstances

**Comment by Fraser999** [comment]
Good stuff 😄
