### ISSUE TITLE
`sign_pub_key_get` throws -1011 error when sign key set was USER_ANYONE

### ISSUE THREAD

**Issue by bochaco** [maidsafe/safe_client_libs#699]
After inserting a permission set in a MutableData with public sign key `USER_ANYONE`, trying to call `sign_pub_key_get` throws error `-1011: Invalid sign public key handle`.

I believe it could/should return an empty string in such a case.

I'm able to reproduce this with safe_app v0.9.0 but also with v0.8.0.

**Comment by m-cat** [comment]
@bochaco Just to be clear, you're calling `sign_pub_key_get` and passing in `USER_ANYONE` and expecting to get an array representations of the key? (`sign_pub_key_get` returns a pointer to an array.)

In this case, I'm not sure what we could sensibly return for `USER_ANYONE`, apart from an error (which seems reasonable to me). Returning a null pointer would mean that the caller has to check for the null pointer before every dereference, and we don't do this anywhere else in the API. On the other hand, returning an empty array doesn't feel right -- `USER_ANYONE` is not a real key handle so we shouldn't be returning an array.

Returning an error makes sense because it's not an actual key handle. Also, the caller can easily check if the handle is `USER_ANYONE`.

Feel free to reopen if you still think this is a bug.
