### ISSUE TITLE
Split out `safe_core` into its own repository

### ISSUE THREAD

**Issue by nbaksalyar** [maidsafe/safe_client_libs#788]
Since `safe_core` does not depend on any other crates in the repository, it doesn't really need to be a part of the workspace. If it needed to be included in `Cargo.toml` as a dependency in the fashion of `safe_core = { path = "../safe_core" }`, it can always be a git submodule.

Pros:
- Will make it easier to maintain `safe_core` in isolation with reduced CI times;
- Will reduce CI times for SAFE Client Libs in general.

Cons:
- More scattered issues and documentation. This can be alleviated by maintaining the issues/wikis only in this repo;
- Any other?

**Comment by ustulation** [comment]
Is workspace only when everything in the workspace depend on each other ? I don't think so but i might be wrong. It just means that they are closely related and changes in one should propagate to the other as quickly as possible. Otherwise if the only time going the workspace way was warranted was when crates depended on each other then for e.g, 10 crates in a workspace all depending on each other seems like a pretty nightmarish proposal.

I agree with the other points - that it should reduce compile times. I have no preferences - if it's helpful and i'm OK for separation.

**Comment by nbaksalyar** [comment]
Agreed. I believe it still _can_ be a part of a workspace being in a separate repo though (and it would make sense since we have a workspace-wide `Cargo.lock`). I'll confirm this and will get back to this issue soon.

**Comment by m-cat** [comment]
Some quick thoughts on this:

I think `safe_core` is still too tightly coupled with `safe_auth` and `safe_app`. Practically every PR to SCL touches `safe_core`, for example [this one](https://github.com/maidsafe/safe_client_libs/pull/1023/files) which theoretically should have only modified `safe_auth` and `safe_app`. For each of these PRs, `safe_core` being in a separate repo would have necessitated separate PRs there.

In general, having our backend crates spread out across different repos has been a maintenance burden for us, and I would prefer not to go too far in that direction. On the [monorepo to multirepo](https://gomonorepo.org/) spectrum, we err a bit too far towards the latter. Personally, I think our multirepo style is quite troublesome, and it's been more apparent recently when we've been making API changes to `safe-nd` or `ffi_utils` and have had to raise a version change in each instance, plus a companion PR in SCL adapting to the new API. 

This process wastes a lot of CI cycles because we have to raise the SCL PR pointing to the temporary `safe-nd` branch to prove that SCL passes CI with the new changes, after which we can merge the `safe-nd` PR, after which we have to update the SCL PR to point to the latest version of `safe-nd`. This also wastes developer time.

Per compile times, in addition to the above point about extraneous CI builds, if a PR doesn't modify `safe_core` then in a perfect world it should not rebuild `safe_core` due to the CI cache. However, most of our PRs *do* modify `safe_core`, so I think this point is moot anyway.

**Comment by nbaksalyar** [comment]
@m-cat, agreed. Either case, the point about slow build times is no longer relevant, and it was the main motivator behind this idea of splitting out `safe_core` into its own repo. Now that we moved to Jenkins, it's not an issue anymore. Closing this.
